import { SpeedInsights } from "@vercel/speed-insights/next"
import '../styles/main.css';
export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}
 
export default function RootLayout({ children }) {
 return (
    <html lang="en">
      
      <body>
      <SpeedInsights/>
        {children}</body>
    </html>
  )
}
